INSERT INTO LIVRO (ID, TITULO, RESUMO, PRECO, NUMERO_PAGINAS, ISBN, DATA_PUBLICACAO, ID_AUTOR,
                   ID_CATEGORIA)
VALUES (1, 'TITULO_TESTE', 'RESUMO_TESTE', 50.0, 250, 'ABCDEF123456', CURRENT_TIMESTAMP, 1, 1);