CREATE SEQUENCE SEQ_AUTOR_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE AUTOR
(
    ID        NUMBER(20) NOT NULL,
    NOME      VARCHAR2(100) NOT NULL,
    EMAIL     VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(300),
    CRIADO_EM TIMESTAMP NOT NULL,
    CONSTRAINT PK_AUTOR PRIMARY KEY (ID)
);
