CREATE SEQUENCE SEQ_ESTADO_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE ESTADO
(
    ID      NUMBER(20) NOT NULL,
    NOME    VARCHAR2(100) NOT NULL,
    ID_PAIS NUMBER(20) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY (ID),
    CONSTRAINT FK_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID)
);
