CREATE SEQUENCE SEQ_ITEM_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE ITEM
(
    ID         NUMBER(20) NOT NULL,
    QUANTIDADE NUMBER(50) NOT NULL,
    LIVRO_ID   NUMBER(20) NOT NULL,
    PEDIDO_ID  NUMBER(20),
    CONSTRAINT PK_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_LIVRO FOREIGN KEY (LIVRO_ID) REFERENCES LIVRO (ID),
    CONSTRAINT FK_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO (ID)
);
