CREATE SEQUENCE SEQ_PEDIDO_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE PEDIDO
(
    ID          NUMBER(20) NOT NULL,
    CPF_CNPJ    VARCHAR2(100) NOT NULL,
    DATA_PEDIDO TIMESTAMP NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID)
);
